name: Build & Test Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build containers
        run: docker-compose build

      - name: Run containers (test mode)
        run: docker-compose up -d

      - name: Wait for app to be healthy
        run: |
          sleep 5
          docker ps
          curl -k https://localhost || exit 1

      - name: Tear down
        run: docker-compose down
