name: Build & Test Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create self-signed SSL cert (if not already there)
        run: |
          mkdir -p certs
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout certs/selfsigned.key \
            -out certs/selfsigned.crt \
            -subj "/CN=localhost"

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 10

      - name: Test HTTPS endpoint from inside container
        run: |
          docker ps
          docker exec $(docker ps -qf "name=nginx") \
            curl -k https://localhost

      - name: Tear down
        run: docker compose down
